### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NKCR-INPROVE/registrdigitalizace#102]
```
Žádám o doplnění uživatelské dokumnentace dle aktuální verze aplikace.
```

Original issue reported on code.google.com by `karel.k...@nkp.cz` on 6 Oct 2011 at 8:53

**Comment by helena-oks** [comment]
Nesplněno po 5 letech, tak nemá smysl.

**Comment by lucka-pavlova** [comment]
Něco je ve Wiki. Možnost rozšířit na základě konkrétních požadavků.
Zavírám.
