### ISSUE TITLE
Navrhnout řešení pro Rezervované dokumenty, které nikdo nezpracovává.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [NKCR-INPROVE/registrdigitalizace#117]
```
Na další schůzku
```

Original issue reported on code.google.com by `pavel.ko...@incad.cz` on 2 Nov 2011 at 7:27

**Comment by lucka-pavlova** [comment]
Je možné filtrovat v rámci GUI Relief. 
Staré neplatné issue. Poslední komentář 2013.
V případě potřeby otevřeme nové issue.
