### ISSUE TITLE
Propojování sklizených UUID se záznamy v tabulce Předloha - MONOGRAFIE (cca 1 MD)

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#576]
Navazuje na ISSUE 322 [https://github.com/incad/registrdigitalizace/issues/322].

Protože se mohou sklízet nejrůznější krameriové, algoritmus by měl být univerzální, jen s určitými odchylkami pro vybrané knihovny. Zde uvedené se bude týkat všech druhů dokumentů s výjimkou periodik (bude zvláštní ISSUE).

Spojování musí probíhat na základě shody údajů podle dohody s knihovnou provozující konkrétního krameria:
Varianta 1 (NK, MZK, asi KNAV): sigla + pole001 + čárový kód 
   (pole 001 je důležité kvůli přívazkům, čárový kód kvůli vícesvazkovým monografiím)
Varianta 2 (knihovny, co v RD čk nemají): sigla+pole001 

Nesmí docházet ke spojení více UUID k jedné předloze - pokud k tomu dojde, je to chybový stav k ručnímu prověření.

Z každého harvestu+spojování by měl odejít mail správci+HD+kontaktní osobě za digitální knihovnu (pokud bude mít zájem).  Měl by obsahovat počet sklizených a počet připojených UUID (podle druhu dokumentu) a výpis nepřipojených UUID a chybových stavů (UUID+001+čk).

**Comment by lucka-pavlova** [comment]
Hotovo. Čeká na testování.

**Comment by lucka-pavlova** [comment]
Uzavře paní Dvořáková po testování.
