### ISSUE TITLE
importní program - drobná úprava zpracování csv

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#596]
Je-li to možné, upravit import csv tak, aby nebylo nutné zachovávat dosavadní počet oddělovačů, na nějž se kontroluje správnost csv. V tabulce, která se do csv převádí, už se některé sloupce dávno nepoužívají. Vystavila bych novou tabulku na novém webu.  Z původní tabulky bych aspoň do csv převáděla menší počet sloupců.

Varianty: 
- kontrola na fixní počet oddělovačů zůstane - místo na 29 na 21
- kontrola nebude, zpracuje se tolik polí, kolik bude vyplněno (asi riskantní, středník v původní tabulce v datech způsobí posunutí všeho)

**Comment by MKortus** [comment]
upravit asi lze.
Preferoval bych variantu jedna. Vzhledem k bezpečnosti dat.
