### ISSUE TITLE
nový web - anglická verze

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#599]
Zakládám samostatné issue, abychom mohli uzavřít infostránky. Nespěchá.

Zatím dotazy:
1. název vlastníka - odkud (z jaké položky v jaké tabulce) se načítá anglický název?  Některé názvy zůstaly česky, i když anglický název v Přispěvateli je (TRE303).
2. nemohl by se odněkud načítat i druh dokumentu anglicky? Mám to někam doplnit?
3.  info soubory, co se nabízejí v editaci z ENG verze, jsou určitě jiné (=v jiném adresáři) než stejnojmenné české? Abych mohla něco zeditovat a něco zneviditelnit nebo vymazat.
-

**Comment by albertoh** [comment]
Preklady se berou s tabulky Lists
1./ opraveno. Ale nektere vlastniky nejsou prelozene v tabulce

2./ pro druh dokumentu neni prelozen zadny zaznam v tabulce

3./ pro editaci anglickych verzi staci prepnout jazyk v admin rozhrani, a tehdy budete pracovat v anglicke lokalizaci

**Comment by helena-oks** [comment]
Děkuji.
1/ Musejí se údaje o vlastníku brát z tabulky DLists, nešlo by to z Přispěvatele? I tam je anglická verze. Protože tam občas údaje měním (třeba kontakty, ale někdy i název), musím to dělat na obou místech. (Samozřejmě na tom netrvám, je-li to složité).

2/ Druh dokumentu přeložím. Ještě by to chtělo vyřešit, jak docílit toho, aby se v reliefu kód naopak nepřekládal (stejně jako se nepřekládá sigla) - knihovníci ty kódy znají. (Dotaz na MK)

3/ Nejde zneviditelnit soubor pouze(!) na ENG větvi - nebudu překládat jednotlivé soubory, v ENG by mělo být jen help, info, seznam institucí a statistika.

**Comment by albertoh** [comment]
1/ Jsou to ruzne zdroje, nezda se mi spravne michat preklady

3/ zneviditelnit polozky menu pouze pro anglickou verzi je vetsi zmena. Radsi nechte tam ceske texty, nebo jen informace typu "work in progress"

**Comment by helena-oks** [comment]
1/ Název Digitální knihovny, na rozdíl od Vlastníka, se nebere z DListu, ale z tabulky Digitální knihovna (takže se to stejně míchá). V tabulce digknih anglický název není. Doplníte tam pole a já ho vyplním? (Jsem ráda, že v DListu nemám DK v rozepsané podobě a že se to nebere odtud, čili zde změnu nechci).  
3/ OK, necháme na "někdy" a issue neuzavřeme

**Comment by helena-oks** [comment]
Jak vyřešíme anglický název Digitální knihovny? Ráda bych to v reliefu doplnila.

**Comment by albertoh** [comment]
Muzeme pouzit list DigKnihovna a prekladat hodnotu. Ted je tam obsah pole "zkratka"

**Comment by MKortus** [comment]
Řešením by asi bylo přidat nové pole pro anglický název.
Pro začátek by v databázi mohla být zkopírována hodnota z názvu, aby se to zobrazovalo správně a až se všechny hodnoty upraví, tak přeindexovat?
Nové pole můžu založit okamžitě, tak aby to hledání mohlo zobrazit, teď jen dohodnout, kdy by se tato změna ve struktuře měla nasadit, aby se hodnoty (názvy) mohly upravit.

**Comment by helena-oks** [comment]
Řešení se mi líbí. Můžu během dneška, max. zítřka, to pole řádně vyplnit,když ho budu mít ve formuláři.

Když už se Digitální knihovna bude brát z tabulky Digknihovna, mohl by se i název instituce brát z tabulky Prispevatel? Tam jsou pole pro český i anglický název a jsou již řádně vyplněna a zkontrolována (což v DListu není).

**Comment by MKortus** [comment]
pro přidání pole do Reliefu je potřeba Relief restartovat, a to se obávám během dne nemohu, ale šlo by to večer. Kdy nejdřív můžu Relief vypnout (na chvíli, předpoklad 10 min max)? šlo by to okolo 17, či raději až okolo 21?

**Comment by helena-oks** [comment]
Dík za přidání a zprovoznění pole nazev_en. Je naplněno správnými texty, prosím přepnout zobrazení. 

(Pozn.  Mám dotaz, jak se to propojení aktualizuje - v reliefu jsem našla a opravila chybu v datech v anglickém názvu Vlastníka v DListu u ABA004 a na webu to pořád vidím špatně. CTRL+F5 u anglické verze nepomůže, vždycky se pak načte česká základní verze)

**Comment by helena-oks** [comment]
V zásadě vyřešeno, otázka názvů v DListu a jiných tabulkách se přenese do samostatného issue.
