### ISSUE TITLE
úprava testu duplicity u přívazků (cca 3 MD)

### ISSUE THREAD

**Issue by ljubkai** [NKCR-INPROVE/registrdigitalizace#605]
V současné době neprobíhá korektně test duplicity u dokumentů (čárových kódů) na něž je přivázáno více titulů (tzv. přívazky). Jako příklad může sloužit č.k. 1001137675, kdy na hlavní titul Václav Němčický  je přivázáno několik dalších titulů 
1.       přívazek: Život svatých apoštolů slovanských Cyrilla a Methodia
2.       přívazek: Obrazy z přírody 
3.       přívazek: Obrazy z přírody s příhodnými povídkami
Při vyhledání duplicity se však zobrazuje výsledek pro jediný a to pro třetí přívazek. Tím vzniká nebezpečí duplicit. .

**Comment by lucka-pavlova** [comment]
Dobrý den,
jedná se o úpravu logiky testu na duplicity. Navrhuji upravit chování, tak aby, když se na základě dotazu pomocí čárového kódu vrátí několik titulů, tak se systém dá na výběr jaký titul, se má deduplikovat.  Vyhovuje Vás tohle řešení?

**Comment by lucka-pavlova** [comment]
V režimu test duplicit, každý dotaz jako samostatný

**Comment by Foltom** [comment]
Zpráva pro Dr. Ljubku - prosím otestovat, abychom mohli uzavřít (dle diskuze během prosincového skype callu). TF

**Comment by helena-oks** [comment]
Otestováno (IL), možno uzavřít.

**Comment by lucka-pavlova** [comment]
Uzavřeno na callu 15.1.
