### ISSUE TITLE
Přihlašování k editaci uživatelských stránek (cca 3 hodiny)

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#611]
1. z některých knihoven, kde mají vlastní login do reliefu, mi psali, že se do RD nemůžou přihlásit - a mysleli tím ten nový web, protože ve starém možnost přihlášení nebyla. Aby tyto zmatky nenastávaly, bylo by možné upravit text v přihlašovacím okénku? Např. misto "Přihlašte se, prosím" třeba "Přihlášení - pouze pro administrátora".

2. z bezpečnostních důvodů, aby mi někdo nezlikvidoval infostránky, bych prosila změnit přihlašovací údaje. Login heldvor nebo adminhd, heslo nejlépe stejné jako mám k tomu loginu v reliefu nebo na serveru.

**Comment by albertoh** [comment]
pridan uzivatel heldvor, heslo mailem

**Comment by helena-oks** [comment]
Děkuji, funguje.
