### ISSUE TITLE
proces spojování předloh a dig. objektů

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#614]
Vytvořit pole pro příznaky pro digitální objekty:

1/ kde došlo k ručnímu spojení, a záznam se programově nemaže
2/ kde se záznam nemá spojovat (URL je v předloze)

**Comment by lucka-pavlova** [comment]
Hotovo. Čeká na test.

**Comment by helena-oks** [comment]
Vytvořena (a již naplněna přes sql) pole "rucnispojeni" a "nespojovat". Možnost jejich zobrazení bude řešeno v dalším issue.
