### ISSUE TITLE
Nové view -  text/tabulka

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#615]
Byli bychom rádi, pokud by bylo možné na HP někde mít "šoupátko" s možností  přepnout výsledky vyhledávání do textového režimu tak, aby se jich vlezlo na stránku co nejvíce. Není potřeba zobrazovat obálku (pro uživatele ano pro do NDK přípravu ale ne) a vypisovat pod sebou Obě Přípravy do NDK zdržuje rolování a listování ve výsledcích, ale chápeme, že pro uživatele je to dobré, takže proto to "šoupátko."

![2](https://user-images.githubusercontent.com/12444931/38247914-147a10c6-3747-11e8-8d98-259f2c0bab64.JPG)

_Toto issue je spoleným požadavkem přípravy NK ČR i MZK ze schůzky 26.3.2018_

**Comment by Foltom** [comment]
Nemá řešení, musela by se řešit jiná šablona. Možnost zvážit tabulkové zobrazení výsledků - prosím nacenit.

**Comment by indrakm** [comment]
Možná by mohlo hodně pomoct i nastavení počtu výsledků na stránku. To by odstranilo nutnost klikání na stránkování. Teď se vypíše tuším 15 výsledků a to je málo. To by molo jít celkem snadno udělat jako nastavovací co a pomůže to.

**Comment by lucka-pavlova** [comment]
Je možné řešit jako nové view - Textové / tabulkové zobrazení. Je potřeba doplnit podrobné zadání. Přejmenovávám na "Nové view -  text/tabulka".

**Comment by lucka-pavlova** [comment]
Prosím o vyjádření MZK, jestli požadavek stále platí, případně o jeho uzavření.

**Comment by indrakm** [comment]
Možné uzavřít. Problém se vyřešil nastavením počtu výsledků na stránku.

**Comment by lucka-pavlova** [comment]
Děkuji za komentář a zavírám.
