### ISSUE TITLE
rozšířené hledání - aktivní oblasti

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#616]
Udělat co nejširší aktivní oblasti v rozšířeném hledání tak, aby se člověk nemusel trefovat do "dvou pixelů". Ideálně aktivní celý obdélník dané konkrétní nabídky.

![3](https://user-images.githubusercontent.com/12444931/38248136-afa8544a-3747-11e8-9d30-280c23a99de9.JPG)

_Toto issue je spoleným požadavkem přípravy NK ČR i MZK ze schůzky 26.3.2018_

**Comment by lucka-pavlova** [comment]
Nereaguje v horní polovině a na labelu.

**Comment by lucka-pavlova** [comment]
Vše mezi horizontálníma čarama.
