### ISSUE TITLE
Tmavší barva ččnb

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#617]
Zkusme prosím zvolit sytější barvu.
![4](https://user-images.githubusercontent.com/12444931/38248305-37f71ef8-3748-11e8-9f48-8600904b402a.JPG)

_Toto issue je spoleným požadavkem přípravy NK ČR i MZK ze schůzky 26.3.2018_

**Comment by pkudela** [comment]
hotovo, pripraveno k testovani

**Comment by helena-oks** [comment]
Prosíme o URL na testovací verzi. http://sluzby.incad.cz/rdcz/home už nefunguje.

**Comment by albertoh** [comment]
Muzete zkontrolovat barvu na produkcnim serveru (toto byla jen kosmeticka zmena)
