### ISSUE TITLE
zobrazení detailu - rolování

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#618]
Zusme nastavit velikost okna podle výsledků bez potřeby rolování. Vím, jde prohledat ctrF, ale bylo by pro přípravu jednodušší orientace.

![5](https://user-images.githubusercontent.com/12444931/38248508-e1a260ca-3748-11e8-95a3-c135f8535c72.JPG)

_Toto issue je spoleným požadavkem přípravy NK ČR i MZK ze schůzky 26.3.2018_

**Comment by Foltom** [comment]
Otázka zvyku - nebude se upravovat.
