### ISSUE TITLE
Vyhledávání podle slov z podnázvu

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#623]
Slova z podnázvu nejsou zařazena do obecného vyhledávání!
Příklad: 
Psallite regi nostro má podnázev "Rozjímání na žalmy pro kněze".

**Comment by lucka-pavlova** [comment]
Přidáme indexaci tohoto pole. Vyžaduje reindexaci.

**Comment by helena-oks** [comment]
Byla jsem přesvědčena, že podnázev jako důležitý údaj už ve starém webu patřil mezi selekční pole, v nichž se vyhledává - pouze se u údajů z tohoto pole nezvyšuje váha. Můžu dostat celkový přehled polí, která jdou do všeobecného vyhledávání? Měla by tam být i edice (jen název edice), ale toto pole se přidávalo později, tak se na něj nejspíš zapomnělo.  

Přeindexování stačí o víkendu.

**Comment by lucka-pavlova** [comment]
Doplit seznam polí, která se indexují. @albertoh

**Comment by albertoh** [comment]
Pole podnazev pridan do hledani pres fulltext (pole _text_ v indexu)
Pole z tabulky preloha, ktera indexujeme jsou
    "id", 
    "nazev as title" (kopirujeme do _text_)
    "podnazev" (kopirujeme do _text_)
    "autor" (kopirujeme do _text_)
    "rokvyd as rokvydstr"  (kopirujeme do _text_)
    "seriename as edice"  (kopirujeme do _text_)
    "rozsah"  (kopirujeme do _text_)
    "cast"  (kopirujeme do _text_)
    "vydavatel"  (kopirujeme do _text_)
    "mistoVyd"  (kopirujeme do _text_)
    "ccnb"  (kopirujeme do _text_)
    "issn"  (kopirujeme do _text_)
    "isbn"  (kopirujeme do _text_)
    "pole001"  (kopirujeme do _text_)
    "idcislo as cislordcz" (kopirujeme do _text_)
    "carkod" (kopirujeme do _text_)
    "cislozakazky" (kopirujeme do _text_)
    "druhdokumentu",
    "rperiodikum",
    "signatura", "cisloper", "bibpoznamka",
    "nvl(financovano, 'neuvedeno') as financovano",
    "sigla1 as vlastnik",
    "urltitul", "urltitnk", "katalog", "url",
    "stavRec as stav"

Krome toho pridavame z ruznych tabulek pole:
  varnazev  (kopirujeme do _text_)
  bibliographich_data
  digknihovna
  nepccnb

**Comment by helena-oks** [comment]
Dík za úpravu. 
K seznamu polí ještě nějaké připomínky a dotazy:
1/ do pole ISBN/ISSN i do pole text by se mělo přidat i nepisbn a nepissn, do pole text nepccnb (to jsem určitě už dřív požadovala)
2/ varnazev by se měl přidat do pokročilého vyhledávání pod název (je-li to problém, není to nezbytné)

3/ To, co není kopírováno do "text" a nemá to svůj řádek v pokročilém vyhledávání, by se asi vůbec indexovat nemělo.  Nebo je to k něčemu jinému? Co je to bibliographicdata?

**Comment by helena-oks** [comment]
Signatura není v text, ale měla by být zachována. Něco slouží jako filtr - financování, druh dokumentu, URL a digknihovna, stavrec - to samozřejmě taky zůstane.

**Comment by albertoh** [comment]
Pridani nepissn a nepisbn vyzaduje zmenu indexeru. (Presunu issue na cerven)
Varnazev jiz je zahrnut v poli nazev v pokrocilem vyhledavani
Nektera pole se pouzivaji pro zobrazeni

**Comment by albertoh** [comment]
bibliographich_data je link do katalogu pod nazvem "Podrobné bib. údaje"
