### ISSUE TITLE
Nastavení počtu výsledků na stránku

### ISSUE THREAD

**Issue by lucka-pavlova** [NKCR-INPROVE/registrdigitalizace#624]
Výběr 10, 20, 50

**Comment by helena-oks** [comment]
Řešení mi připadá jako vyhovující - uzavřít issue by ale měli původci požadavku z MZK.

**Comment by indrakm** [comment]
Ano, mně přijde také vyhovující. Děkuji. Měl jsem dovolenou, takže zavírám až nyní.

**Comment by lucka-pavlova** [comment]
Zavřeno na schůzce 18.9.2018.
