### ISSUE TITLE
soubory ke stažení z INFO - přenést na nový server

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#627]
Soubory ke stažení na info stránkách (odkaz na staré umístění) už nejsou dostupné. Prosím umístit jinam a poslat link. 

Dva soubory připojuji (trochu jsem je upravila) - příponu je nutno změnit na xls!!! 

Soubor   export_rd.tar.gz nikde u sebe nemám, prosím nahledat někde z vašich záloh.

[RD_prispevatel.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2057308/RD_prispevatel.txt)
[RD_hlaseni_tabulka.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2057309/RD_hlaseni_tabulka.txt)

**Comment by albertoh** [comment]
Soubory jsou tam. Spravne linky na ne:

http://registrdigitalizace.cz/rdcz/file?action=GET&id=RD_pripevatel.xls

http://registrdigitalizace.cz/rdcz/file?action=GET&id=RD_hlaseni_tabulka.xsl

**Comment by helena-oks** [comment]
Odkazy nefungují (ani samostatně). Tabulka hlášení má navíc špatnou příponu a ještě potřebuju soubor export_rd.tar.gz.

**Comment by albertoh** [comment]
Ano, chyba v odkazech. Spravne:

http://registrdigitalizace.cz/rdcz/file?action=GET&id=RD_pripevatel.xls

http://registrdigitalizace.cz/rdcz/file?action=GET&id=RD_hlaseni_tabulka.xsl

export_rd.tar.gz je tam take:

http://registrdigitalizace.cz/rdcz/file?action=GET&id=export_rd.tar.gz

Na serveru jsou zkopirovane vsechny soubory z puvodniho webu: 
export_rd.tar.gz
RD_hlaseni_tabulka.xls
RD_hlaseni_tabulka_orig.xls
rd_jak_hledat.pdf
rd_jak_vyplnit_tabulku_hlaseni.pdf
rd_jak_ziskat_cCNB.pdf
RD_prispevatel.xls
rd_registr_digitalizace.pdf
RD_uzivatel_admin.xls
test.pdf

Muzete se k nim dostat zmenou parametrem id

**Comment by helena-oks** [comment]
Už funguje stahování export_rd.tar.gz. 

Link na prispevatel.xls nefunguje. Link na hlášení funguje, ale je tam starý soubor - prosím tyto 2 soubory vyměnit za upravené verze v příloze tohoto issue.

**Comment by albertoh** [comment]
Omlouvam se, chybi s:
http://registrdigitalizace.cz/rdcz/file?action=GET&id=RD_prispevatel.xls

Nove soubory jsou tam

**Comment by helena-oks** [comment]
Díky, funguje. Ale zjistila jsem chybku v tabulce hlášení, tak prosím nahradit připojeným souborem (též se omlouvám). Opět nutno změnit příponu na xls.
[RD_hlaseni_tabulka.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2067524/RD_hlaseni_tabulka.txt)

**Comment by albertoh** [comment]
Je to tam:
http://registrdigitalizace.cz/rdcz/file?action=GET&id=RD_hlaseni_tabulka.xls

**Comment by helena-oks** [comment]
Děkuji!
