### ISSUE TITLE
test duplicity - odříznutí koncové interpunkce z údajů získaných z katalogu aleph

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#629]
Při zadání ČK v režimu test duplicity proběhne vyhledání v katalogu Aleph a je vrácen obsah pole 245a, který se stane rešeršním dotazem pro RD. Na konci tohoto podpole bývá ovšem interpunkce (lomítko, dvojtečka, středník,tečka).  Pokud zůstává interpunkce v dotazu, neuplatní se zvýšení váhy pro "dotaz=název" nebo "dotaz=začátek názvu" a i přesná shoda (bez interpunkce) se může ocitnout až hluboko pod záznamy, které pouze obsahují příslušná slova z dotazu.

Příklad: 
ČK 1000444387 = Člověk a jeho svět. II, Lidské rasy. 
V tomto případě dotaz obsahuje na konci tečku. Záznam by se měl zobrazit ihned pod záznamy, kde je "Člověk a jeho svět" čistým názvem. tj. jako 6. v pořadí. Kvůli tečce se zobrazí až jako 17. v pořadí, až na další stránce. Při velkém množství nalezených záznamů (zejména je-li názvem jen jedno slovo) je třeba prohledávat několik stránek, při menší pozornosti dojde k přehlédnutí a může vzniknout i duplicita. 

Požadavek: převést údaje získané z Alephu na tvar bez konečné interpunkce (nebo potlačit veškerou interpunkci).

**Comment by helena-oks** [comment]
Výsledky jsou mnohem lepší, přesto bych to odřezávání uvítala. Issue 605 je hodně složitý požadavek, nevím, jestli to s ním spojovat. Otestovat, vyjádřit se k tomu a issue uzavřít musí pan Ljubka.

**Comment by lucka-pavlova** [comment]
Zavřeno na schůzce 18.9.2018.
