### ISSUE TITLE
odpojování digobjektu od předlohy + úpravy ve formulářích digobjektů

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#631]
Prosím o nástroj k odpojení nesprávně napojeného digobjektu od předlohy - pro případy, kdy má zůstat jak záznam předlohy, tak digobjektu. Ve formuláři digobjektu by bylo potřeba zobrazit příznaky "ruční spojení" a "nespojovat" a pokud možno - jako needitovatelné - i číslo záznamu předlohy (raději idcislo než id).  Tato příznaková pole by mělo být možné i přidat do tabulky pro zobrazení a jako filtr.

Souvisí s https://github.com/NKCR-INPROVE/registrdigitalizace/issues/614

**Comment by lucka-pavlova** [comment]
Uprava formulářů, Odpojování pomocí BF, Testování cca 2MD

**Comment by lucka-pavlova** [comment]
Odpojení je možné provést i pomocí stávajících nástrojů Reluefu, proto bude tvorba funkce zatím pozastavena. Pole "ruční spojení" a "nespojovat"  budou doplněna do konce června.

**Comment by helena-oks** [comment]
Děkuji, odpojování i editace přes formulář zcela vyhovuje.

**Comment by helena-oks** [comment]
Přidat ve formuláři příznak "nespojovat" není možné? Chtěla jsem ho přidat UUID fd2c5520-1fb9-11e5-bcc5-5ef3fc9bb22f.  Při editaci předloh narážím občas na vícesvazková díla, která nikdy spojit nepůjdou. Pokud to nejde, budu je muset syslit pro příští sql dávku...

**Comment by MKortus** [comment]
Momentálně nikoliv. Pole jsou pouze  pro zobrazení. Mám dojem že jsme se tak domlouvali. Že je uvidíte, a dá se podle nich filtrovat, ale editovatelné být neměly.
Teoreticky je můžeme udělat editovatelná pouze pro administrátora (či jinou pevně definovanou a omezenou skupinu), ale obecně si myslím že by editovatelné být neměly.
