### ISSUE TITLE
Pridani nepissn a nepisbn -  vyzaduje zmenu indexeru.

### ISSUE THREAD

**Issue by lucka-pavlova** [NKCR-INPROVE/registrdigitalizace#632]

**Comment by helena-oks** [comment]
Neplatná ISBN se nevyhledají. A jak se ukázalo, ani všechna nejsou v NEPISBN (za tím účelem zakládám zvláštní issue).

Příklad: 
80-86389-39-1  - v NEPISBN je, pochází z 020z - nevyhledá se (Teorie mravních citů 2005)

**Comment by lucka-pavlova** [comment]
Testování čeká na změny v importním programu, issue #636

**Comment by helena-oks** [comment]
Prověřila jsem na testovacích záznamech. Údaje z tzv. neplatných ISBN (z tabulky NEPISBN, některá ve skutečnosti neplatná nejsou, ale nemůžeme mít 2x platné) se vyhledávají z pokročilého vyhledávání z pole ISBN, ale nevyhledávají se z obecného vyhledávacího políčka. 

Zjistila jsem, že podobné je to s neplatným ččnb (NEPCCNB). Je problém ty údaje nechat vyhledat oběma způsoby? Pokud by se platné ISBN i platné ČČNB vyhledávaly také pouze ze speciálního pole, bylo by to v pořádku, takhle to uživatele mate (je zvyklý, že ČČNB i ISSN z obecného pole vyhledá, a když má k dispozici pouze ten neplatný údaj a nenajde se to, je přesvědčen, že to tam není...)

**Comment by lucka-pavlova** [comment]
Alberto, prosím okomentuj stav. Díky

**Comment by lucka-pavlova** [comment]
V Reliefu upraveno (data OK), je potřeba upravit hledání.

**Comment by lucka-pavlova** [comment]
@albertoh prosim okomentuj.

**Comment by albertoh** [comment]
Lze vyhledat neplatne isbn/issn i z obecneho pole

**Comment by helena-oks** [comment]
Děkuji, vše OK, možno uzavřít.
