### ISSUE TITLE
opravy přes sql dávku

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#633]
Prosím spustit dávku v příloze.
[siglyOSA2.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2115081/siglyOSA2.txt)

**Comment by helena-oks** [comment]
Pozapomenuto - prosím vyřídit.

**Comment by MKortus** [comment]
Výsledky jsou následující. Celkem zpracováno 179 řádků z 181 updatovacích řádků. 
U následujících podmínek byl počet záznamů různý od 1:
0 rows updated.      pole001='000599033' and ccnb='cnb000803675'
2 rows updated.      pole001='000489228' and ccnb='cnb002162366'
0 rows updated.      pole001='000572846' and ccnb='cnb002482337' -- tato řádka tam byla 2x
0 rows updated.      pole001='000728717'
