### ISSUE TITLE
úpravy přes sql dávky

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#635]
Prosím spustit dávky z příloh a zprávu, pokud nějaké opravy neproběhnou.
[urltit08.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2301624/urltit08.txt)
[nespoj08.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2301625/nespoj08.txt)
[siglyOSA3.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2301626/siglyOSA3.txt)

**Comment by MKortus** [comment]
urltit08 prošely všechny záznamy (1118 zazálohováno)
siglyOSA3 prošly všechny záznamy (76 zazálohováno)
nespoj08 - 4 záznamy nebyly změněny (483 záznamů zazálohováno - 1118 řádek v souboru)

seznam nezpracovaných záznamů:
update digobjekt set nespojovat=1 where uuid='c8aa9220-9190-11e8-9588-5ef3fc9bb22f';    0 rows 
update digobjekt set nespojovat=1 where uuid='c8aa9220-9190-11e8-9588-5ef3fc9bb22f';    0 rows 
update digobjekt set nespojovat=1 where uuid='c8aa9220-9190-11e8-9588-5ef3fc9bb22f';    0 rows 
update digobjekt set nespojovat=1 where uuid='d7ab55a0-8445-11e8-9588-5ef3fc9bb22f';    0 rows 

koukal jsem, že uuid se v souboru opakovala (rovnou pod sebou). Například u těchto nezpracovaných jsou první 3 shodné. Některé jsem zahlédl i 8x.

**Comment by helena-oks** [comment]
Děkuju. Je to v pořádku, ty 2 uuid jsem nejspíš mezitím kvůli vyřazení záznamu předlohy smazala. Jen vždy zapomenu ty uuid "unikovat", když je vybírám ze souboru pro urltitul...
