### ISSUE TITLE
mapování z marcxml do tabulky NEPISBN

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#636]
Z xml do NEPISBN se nepřevádějí další výskyty 020 (podpole a i podpole z), ani obsah všech výskytů pole 902a. Zřejmě tam v současnosti jde pouze 020z (z prvního výskytu).

Ohledně pole 020 je vše dobře popsáno v issue 182, comment 11.8.2015.
O zařazování všech výskytů 902a do NEPISBN jsem žádat chtěla dodatečně, ale bohužel to nemůžu najít ani v poště, ani v issues, takže jsem možná nakonec požadavek nezadala. Prosím tedy, když už se budou opravovat chyby, aby byl zapracován i tento doplněk.

Příklady: 
80-86389-39-1  - v NEPISBN je, pochází z 020z  (Teorie mravních citů 2005)
978-80-86783-47-5 - 2.výskyt 020(a), v xml je - není v NEPISBN (Ozdobné balení dárků, 2011)
978-80-87173-28-2 - pole 902a, v xml je - není v NEPISBN (TGM - život, dílo a odkaz pro současnost)

**Comment by SykoraLukas** [comment]
Otestováno a nasazeno.

**Comment by helena-oks** [comment]
Výsledky testování OK, dík.
