### ISSUE TITLE
omylem smazaný soubor HELP na webu

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#637]
Prosím obnovit ze zálohy soubor http://www.registrdigitalizace.cz/rdcz/napoveda - pokud možno co nejdříve.

Omylem jsem ho přepsala v úmyslu zkusit založit nový soubor.  Mám možnost to udělat, pokud ano, jak? Pokud ne, bylo by možno pro mě založit soubor "digbohemika" na úrovni nápověda a info?

**Comment by albertoh** [comment]
Z nejakeho duvodu nemuzu se pripojit na server 10.1.20.48. Tam by mela byt kopie.

**Comment by helena-oks** [comment]
Ani já se tam nedostanu, už jsem to zkoušela předtím. Na ...incad.sluzby... se taky nedostanu - není tam něco? 

Zálohují se ty infostránky aspoň občas, nebo je tam jen kopie z doby spuštění? Může dojít i k nějaké větší havárii, nerada bych to dělala celé znovu a zejména v přehledu institucí změny dělám docela často. Zálohování 1x měsíčně by stačilo.

**Comment by albertoh** [comment]
Obnovil jsem kopie z dobu spusteni.
Zalohy je mimo nas.

**Comment by helena-oks** [comment]
Děkuji za záchranu :-)
