### ISSUE TITLE
neaktualizuje se uživatelský web?

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#639]
Záznam Pr000387805 má na webu zastaralé údaje (např. financování, URL) - v reliefu byl aktualizován 31.8. Probíhají aktualizace???

**Comment by albertoh** [comment]
Stale nemam pristup na server, kde bezi indexace

**Comment by helena-oks** [comment]
Můžete vyzkoušet, jestli už se připojíte, a když jo, oživit ty aktualizace?

**Comment by albertoh** [comment]
Bohuzel nemuzu

**Comment by helena-oks** [comment]
Dostala jsem (po urgenci) od našeho IT zprávu, že by snad měl problém přístupových práv vyřešit pan Dolejš.

**Comment by albertoh** [comment]
Uz jsem se tam dostal.
Indexacni proces byl spadly, (OutOfMemory error).
Uz bezi a index je aktualizovan.
