### ISSUE TITLE
doplnění přes sql dávky

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#640]
Prosím spustit soubory příkazů sql v příloze + výmaz záznamů digobjektů podle uuid v souboru uuid-deakt-08.txt (tyto uuid nemusí už všechny v RD existovat).  

[nespojMZK.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2365694/nespojMZK.txt)
[urltit08a.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2365695/urltit08a.txt)
[nespoj08a.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2365696/nespoj08a.txt)
[rucne08a.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2365697/rucne08a.txt)
[urltitMZK.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2365698/urltitMZK.txt)
[ccnb_dod0818.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2365699/ccnb_dod0818.txt)
[uuid-deakt-08.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2365700/uuid-deakt-08.txt)

.

**Comment by MKortus** [comment]
Zpracováno s následujícími vyjímkami.
v souboru nespoj08a.txt se nezpracovaly tyto záznamy:
update digobjekt set nespojovat=1 where uuid='132d4e50-93da-11e8-be68-5ef3fc9bb22f';
update digobjekt set nespojovat=1 where uuid='97fbf160-7eed-11e8-bb44-5ef3fc9ae867';
update digobjekt set nespojovat=1 where uuid='aa4d88a0-90d2-11e8-9588-5ef3fc9bb22f';
update digobjekt set nespojovat=1 where uuid='b9135940-8377-11e8-be68-5ef3fc9bb22f';

v souboru ccnb_dod0818.txt se nezpracoval záznam:
update predloha set edidate=to_date('11.09.2018','dd.mm.yyyy'),ediuser='heldvor',ccnb='cnb000454903' where sigla1='BOA001' and pole001='000940064';
