### ISSUE TITLE
sklízení ABG001 - dočasně zablokovat

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#641]
Prosím zastavit - ještě dnes - sklízení dat ABG001 (MLP) přes OAI. Až bude možno opět spustit, nahlásím to touto cestou.

**Comment by MKortus** [comment]
Zablokováno, importer restartován

**Comment by helena-oks** [comment]
Prosím obnovit sklízení ABG001. Děkuji.

**Comment by MKortus** [comment]
obnoveno a restartováno.
