### ISSUE TITLE
kontrola na duplicitu - přes ČK Slovanské knihovny

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#642]
Je třeba upravit kontrolu na duplicitu, aby přes čárové kódy začínající 3 proběhlo vyhledání v katalogu SLK, tj. bázi SLK01.

**Comment by lucka-pavlova** [comment]
@albertoh prosím odhadni čas.

**Comment by helena-oks** [comment]
Funguje, možno uzavřít.
