### ISSUE TITLE
doplnění přes sql dávky

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#646]
Prosím spustit dávky v příloze.
[opravy-knav_se.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2477761/opravy-knav_se.txt)
[abg001_uuid_dopl.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2477762/abg001_uuid_dopl.txt)

**Comment by helena-oks** [comment]
Jestli akce ještě neproběhla, můžu poprosit dodat k přikazům v souboru opravy-knav ještě podmínku  "and stavrec='finished'?

**Comment by helena-oks** [comment]
Omlouvám se a beru zpět. Špatně jsem pochopila požadavek KNAV, naopak by se měl všem záznamům, co ho dosud nemají, změnit stav na finished, ale jestli se s tím musí dělat ještě něco navíc, pak změnu stavu udělám poté online.

**Comment by MKortus** [comment]
opravy-knav: editováno celkem  8802 záznamů, neexistuje záznam: 
  sigla1='ABA007' and pole001='000598114' and issn='0577-3652';

abg001: zpracováno 385 záznamů, neexistují záznamy kde pole001 je rovno jedná z následujících hodnot (47 záznamů):
'152326', '175999', '2055685', '2066329', '2068515', '2071594', '211283', '2178851', '2209013', '2214900', '2216041', '2216127', '2216169', '2216172', '2219780', '2230193', '2230198', '2230216', '2230217', '2230218', '2230219', '2230224', '2230408', '2230418', '2230420', '2230423', '2230424', '2230425', '2235752', '223616', '248984', '261490', '262782', '266061', '266543', '283854', '283856', '284341', '284385', '284619', '284669', '2848412', '296668', '3838098', '3991237', '4033916', '89766'
