### ISSUE TITLE
editace informační stránky digbohemika nefunguje

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#653]
Stránku digbohemika, která se volá z Další zdroje (byla nedávno přidaná) nelze editovat. Resp. editace se zdaří a uloží, ale i po reloadu se zobrazuje stará verze. Při opětném zavolání k editaci je zde opět stará verze!
(Původní verze: poděkování v závorce na konci, nová verze: poděkování pod nadpisem + další úpravy.)
Jiné stránky se editují normálně, včetně stránky Help.

Nápravu prosím spojit s požadavkem 652 - prosba o vytvoření (editovatelného!) souboru  digANNO.

**Comment by helena-oks** [comment]
Toto je chyba, prosím o brzkou nápravu!

**Comment by albertoh** [comment]
Editoval jsem stranku digANNO ("Test digANNO"), zmenil jsem digbohemika (odstranil jsem zavorky, v cestke a angl. verzi), a vidim zmeny.

**Comment by helena-oks** [comment]
Děkuji za nápravu - ještě ve čtvrtek ráno to určitě nefungovalo.
