### ISSUE TITLE
uživatelský web - ztratil se "překlad" názvu digitální knihovny

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#655]
V boxu Digitální knihovna se nezobrazuje název digitální knihovny, ale její kód, který je uživatelům nesrozumitelný (např. digknihovna.ABA001c-DK má být GoogleBooks).  Původně tam byl "překlad" z tabulky digknihovna. Nevím, od kdy se to ztratilo, ale v anglické verzi to přeložené je.

**Comment by albertoh** [comment]
Opraveno
