### ISSUE TITLE
přidání sčítacího kódu pro toplist do uživatelského webu

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#659]
Prosím přidat do patičky kód pro toplist.cz:

<a href="https://www.toplist.cz"><script language="JavaScript" type="text/javascript">
</script><noscript><img src="https://toplist.cz/count.asp?id=1788589" border="0"
alt="TOPlist" width="88" height="31" /></noscript></a>

**Comment by helena-oks** [comment]
Pokus vložení jako kód:
`<a href="https://www.toplist.cz"><script language="JavaScript" type="text/javascript">
</script><noscript><img src="https://toplist.cz/count.asp?id=1788589" border="0"
alt="TOPlist" width="88" height="31" /></noscript></a>`

**Comment by helena-oks** [comment]
Pošlu mailem.

**Comment by albertoh** [comment]
Aplikace uz pouziva Google Analytics

**Comment by lucka-pavlova** [comment]
Na callu 15.1.2019 bylo dohodnuto :  Naimplementovat bez ikony s nižší prioritou.

**Comment by helena-oks** [comment]
Děkuji, funguje.
