### ISSUE TITLE
přidání sufixu pro financování pro XML import 

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#660]
Prosím o úpravu importního programu - přidání dalších sufixů pro název XML souboru, aby se doplnil kód financování. Jde o analogii _own -> vlastni. Pro jistotu ošetřit, aby sufix mohl být velkými i malými písmeny. Platí pro jakoukoli siglu.

1/ sufix _msvk -> kód MSVK 
2/ sufix _visk7 -> kód VISK7

**Comment by SykoraLukas** [comment]
Dobrý den,
změna nasazena. Můžete odeslat testovací soubor.
