### ISSUE TITLE
sklízení RD do Knihovny.cz

### ISSUE THREAD

**Issue by zabak** [NKCR-INPROVE/registrdigitalizace#664]
Bylo by možné sklízet obsah RD do portálu Knihovny.cz? Jde mi hlavně o identifikátory a linky do Krameria, spíš jako kontrolu než že bychom to samostatně prezentovali. Stačí formou jednorázových kompletních exportů databáze jednou za čas. Šlo by? Nebo jestli na to už máte nějaké API?

**Comment by lucka-pavlova** [comment]
Prosim zjistete moznosti Webservice.

**Comment by lucka-pavlova** [comment]
@zabak , napište prosím seznam polí, které byste chtěli mít v exportu.

**Comment by zabak** [comment]
V ideálním případě kompletní záznamy včetně všeho. Ale nevím co vlastně máte za pole :-)

**Comment by SykoraLukas** [comment]
Posílám seznam polí, která můžeme poskytnout (po konzultaci s @lucka-pavlova  a @Foltom)

[RdExport20190307.zip](https://github.com/NKCR-INPROVE/registrdigitalizace/files/2941984/RdExport20190307.zip)

**Comment by zabak** [comment]
@SykoraLukas tohle vyhovuje

**Comment by zabak** [comment]
Jaký bude další postup? Budete dělat webservice?

**Comment by SykoraLukas** [comment]
Ne, udělám vám export záznamu z databaze

**Comment by zabak** [comment]
Export vypadá použitelně, můžete udělat kompletní export?

**Comment by SykoraLukas** [comment]
@zabak nebylo by pro vas lepší mít přístup do databáze, k view udělanému pro tyto pole? Celkem je v databázi přes 500 tisíc záznamů a velikost takového souboru by byla obrovská

**Comment by zabak** [comment]
Zas tak velké by to nebylo, běžně pracujeme se soubory obsahujícími i miliony záznamů. Když to budu tahat přímo z databáze, tak budu muset mít přístup na daný server a tam si budu muset napsat exportní skript, který už máte hotový navíc tam budu stejně potřebovat i místo na disku abych si to odtud mohl stáhnout.

**Comment by zabak** [comment]
Díky, zítra stáhneme.

**Comment by zabak** [comment]
@SykoraLukas narazili jsme na problém - ty MARC záznamy jsou nějaké ukousnuté. níže na ukázku konec prvního marc záznamu z CSV, který končí <sub" a pokračuje další údaj toho csv. 

Je to proto, že to máte takto ukousnuté i v databázi, nebo je to jiná chyba? 

```
   <datafield ind1=""4"" ind2=""1"" tag=""856"">
         <sub","Kníže Igor","Borodin, Aleksandr Porfir'jevič","Praha","Alois Wiesner","1899","","BK","norskeFondy","ABA001","http://kramerius.nkp.cz/kramerius/handle/ABA001/11982288","84 s."
"1001137702","54 H 0000046/Č.106-107","NKC01","001810905","nkc20081810905","<?xml version=""1.0"" encoding=""utf-8""?><collection>

```

**Comment by SykoraLukas** [comment]
Děkuji za upozornění, nenapadlo mě, že velikost polí v csv souboru je omezená. V databázi je to uložené v pořádku, pracuji nyní na novém exportu.

**Comment by zabak** [comment]
Udělejte klidně samostatný export xml do jednoho souboru a vedle toho csv, kde bude jen identifikátor každého xml záznamu.

**Comment by SykoraLukas** [comment]
Poslal jsem vám pře uschovna.cz novou verzi exportu.

**Comment by lucka-pavlova** [comment]
Je možno uzavřít?

**Comment by lucka-pavlova** [comment]
Uzavřeno na schůzce 16.7.2019
