### ISSUE TITLE
sklízení CBA001 přes OAI - neprobíhá

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#665]
Prosím prověřit, proč se CBA001 nesklízí, a spustit harvester (tak, aby se dohonilo, co sklizeno nebylo).

http://katalog.cbvk.cz/i2/i2.ws.oai.cls?.....

**Comment by lucka-pavlova** [comment]
Prosim zjistete stav indexeru.

**Comment by SykoraLukas** [comment]
Je sklizeno, prosím o kontrolu dat

**Comment by helena-oks** [comment]
Z dávek CBA001 z 19.2. (ruční import) žádný záznam neprošel a všechny byly odmítnuty, ale to je v pořádku, protože jejich skutečně nové záznamy se importovaly již 11.2.   Podle údajů v tabulce Importy dat zřejmě i tehdy šlo o ruční import, protože je tam toho dne několik neúspěšných pokusů.  

Sklizeň tedy probíhá, ale import má problém - chyba parsování dat. Můžete vykomunikovat se správcem CBA001  - nechvatal@cbvk.cz - co jste musel upravovat, aby parsování prošlo? Prosím dát do kopie.

**Comment by lucka-pavlova** [comment]
domluvit se s panem Nechvatalem na kontrolnim vzorku dat a doladit sklizeň.

**Comment by lucka-pavlova** [comment]
Bude řešeno pomocí FTP, čekáme dodání dat z CBA001

**Comment by helena-oks** [comment]
Vzhledem k problémům s formátem dat pro FTP by bylo lepší vrátit se k OAI. Prosím vyzkoušet doporučení ing. Nechvátala z CBA001:

Pokud se XML stahuje pomocí utility wget, nainstalovat novou verzi - https://ftp.gnu.org/gnu/wget/. Umí pracovat s https.

**Comment by helena-oks** [comment]
Poslala jsem na ftp testovací soubor cba001_z_test.xml se vzorkem získaným ze zaslaných dat a mnou ručně upraveným do standardní podoby. Neprošel s touto chybovou hláškou:
"Soubor nebyl importován. Nastala chyba při načtení souboru. Chyba: Invalid byte 2 of 3-byte UTF-8 sequence". 
Prosím zjistit, co to způsobilo, protože nemůžu od ing. Nechvátala pořád požadovat další úpravy dat.

**Comment by helena-oks** [comment]
Ing. Nechvátal upravil data pro ftp do podoby, která by měla projít. Nicméně převod marctagů do formátu pro relief se nezdařil. Prosím prozkoumat, co je v souborech nezpracovatelné. Šlo o 2 soubory cba001_h_2019-04-24...xml. Pokus o import dnes. Poznámka: adresář cba001r na ftp se stále nevybírá, musela jsem soubory přemístit do skc001r.

**Comment by helena-oks** [comment]
Formát záznamů na ftp, aby je importní program zpracoval, jsme nějak vyřešili s ing. Nechvátalem.

Issue bude možno uzavřít teprve až bude nastaveno automatické vybírání adresáře cba001r na ftp. (Opět jsem ho musela vyprázdnit; dalši data budou příští neděli).

**Comment by SykoraLukas** [comment]
V importeru je nastaveno adresa cba001r/importMARCXML stejne jako je to u jiných ftp. Můžete prosím zkontrolovat, že jde o správnou spložku?

**Comment by helena-oks** [comment]
Nakopírovala jsem tam zpět jejich poslední soubory k importu - můžete sledovat, jestli je program vybere? Kdy se spouští sbírání z ftp adresářů pro jiné sigly než ABA001 a BOA001?

![obrazek](https://user-images.githubusercontent.com/13746425/60887393-93ac3580-a254-11e9-87c4-c630058ddf0d.png)

**Comment by SykoraLukas** [comment]
Bohužel nemohu, nedostanu se do této složky. Sbírání se spouští jednou za hodinu (ABA001 a BOA001 jednou za 10 minut). Ale budu se divat co importer dela

**Comment by lucka-pavlova** [comment]
Lukáš dostane od p. Dvořákové přístup do adresáře a zkontroluje práva atd.

**Comment by helena-oks** [comment]
Sklízení bylo vyřešeno - chyba v loginu. Případné úpravy zpracování budou v novém issue na gitlabu.
