### ISSUE TITLE
zobrazování smazaných uuid v uživatelském rozhraní

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#666]
Z uživatelského rozhraní se zobrazují odkazy do krameria i v případě, že v tabulce digobjekt je záznam s příslušným uuid smazán. Jde o situace, kdy šlo o duplicitní digitalizaci a jeden záznam předlohy a jeho uuid byly smazány. U zachované předlohy se zobrazují dva odkazy do krameria - platný i ten nefunkční.

Příklad: Pr000176523
select * from digobjekt where uuid='12eed860-fb5d-11e3-89c6-005056827e51'; není 
select * from digobjekt where uuid='a4503b70-18bb-11e4-8f64-005056827e52'; je

**Comment by lucka-pavlova** [comment]
@albertoh , prosím zkontroluj hledání, V Reliefu jsou tyto data smazaná.

**Comment by albertoh** [comment]
Opraveno

**Comment by helena-oks** [comment]
Zkontrolováno, dík za opravu.
