### ISSUE TITLE
zobrazování odkazů do obou dig. knihoven NDK

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#669]
Bylo by vhodné, aby se k záznamům v uživatelském RD připojovalo URL do dig. knihoven NK i MZK. Pokud se získalo URL do krameria NK sklizní, stačilo by vytvořit druhý odkaz do krameria MZK přidáním prefixu MZK k témuž UUID.  Platilo by to ovšem pouze pro záznamy, které mají kód financování iop nebo ndk-u.

**Comment by lucka-pavlova** [comment]
@albertoh , prosím odhadni pracnost změny.

**Comment by albertoh** [comment]
Asi nerozumim zadani.
Pri hledani zaznamu obou digitalnich knihoven, vysledky maji linky do NKP a MZK. Viz:

http://registrdigitalizace.cz/rdcz/results;q=*;start=0;rows=10;sort=score%20desc;filters=%5B%7B%22field%22:%22digknihovna%22,%22value%22:%22ABA001-DK%22%7D,%7B%22field%22:%22digknihovna%22,%22value%22:%22BOA001-DK%22%7D%5D;adv=%7B%22title%22:%22%22,%22autor%22:%22%22,%22rokvyd%22:%22%22,%22isxn%22:%22%22,%22ccnb%22:%22%22,%22signatura%22:%22%22,%22carkod%22:%22%22,%22cislordcz%22:%22%22,%22pole001%22:%22%22,%22vydavatel%22:%22%22,%22can%22:%22%22%7D;collapse=cnb_collaps

Neni to, co popisete?

**Comment by helena-oks** [comment]
Značné množství dokumentů má linky do obou knihoven, protože u toho, co zdigitalizovala MZK, jsme párkrát odkazy do DK-MZK doplňovali do předlohy (sql příkazem), a odkazy do DK-NK se připojily sklizní krameria NK. Jen v těch případech se zobrazují oba linky. Novější věci oba linky nemají, např. ten Domov pro lásku. To, co zdigitalizovala NK, má vždy pouze jeden link, a to ze sklizně.

Filtr na záznamy financováno= udržitelnost (relativně nové), z obou knihoven (URL nemusí být vůbec):
celkem 80720
ABA001 + DK NK = 23208 (sklizeň)
BOA001 + DK MZK = 8981 (URL v předloze)
BOA001 + DK NK = 45007 (sklizeň)
ABA001 + DK MZK = 1 (asi omyl)
Nedosáhneme toho, aby všechno z NK i MZK mělo linky do obou DK (u vícesvazkovek a seriálů  nemůže dojít ke spojení sklizně s předlohou), ale naprostá většina by to mít mohla.

**Comment by lucka-pavlova** [comment]
Alberto prosím doplň odhad pracnosti

**Comment by lucka-pavlova** [comment]
@albertoh prosim okomentuj.

**Comment by albertoh** [comment]
Takze, ukol je VZDY zobrazit linky do obou DK ikdyz v reliefu nejsou?

**Comment by helena-oks** [comment]
Do budoucna by se do tabulky Predloha linky typu NDK dávat neměly (až na periodika a výjimky, kde se to musí dělat ručně, protože spojení s výsledky sklizně udělat nejde) - měly by se tam napojovat z tabulky Digobjekt. 
Jinak formulováno: 
kde existuje spojení mezi předlohou a digobjektem sklizeným z NDK a tam, kde má předloha zároveň ve financovano hodnoty "iop" a "iop-ndku", tam připojit zobrazení URL 2x:  jednou doplnit prefix pro NDK-NK a jednou pro NDK-MZK (bez ohledu na to, zda je vlastník předlohy ABA001 nebo BOA001; sigla v digobjektu by ale měla být jedině ABA001/ABA000/BOA001, aby se do toho nemotaly sklizená uuid z KNAV). 
Prefix pro NDK-MZK je http://www.digitalniknihovna.cz/mzk/uuid/uuid:
Prefix pro NDK-NK je zatím http://kramerius4.nkp.cz/search/handle/uuid:

Je možné, aby se prefixy někde nastavily a daly by se snadno změnit? Řeší se různé klienty krameriů a není jisté, které URL bude pro NDK-NK zvoleno, je třeba to otestovat.
Pokud ano, prosím nastavit pro NDK-NK: http://krameriusndk.nkp.cz/uuid/uuid:

**Comment by helena-oks** [comment]
Kde je to připraveno, na nějakém testovacím webu? Prosím URL.

**Comment by albertoh** [comment]
Je to na ostrem serveru.
Napriklad, hledani cnb001287005 vrati jeden zaznam. Pod nim jsou videt 3 dig. objekty, ikdyz v reliefu mame 2.

**Comment by helena-oks** [comment]
Odkazy se zobrazují, ale něco není v pořádku - zmizela většina záznamů napojených na digitální knihovnu NK (ABA001-DK), kam se až dosud napojovalo vše, co se linkuje ze sklizených objektů (celkem to bude teď více než 50000, viz čísla v předchozím commentu). Všechny záznamy, co budou mít ty 2 odkazy, by měly spadat do ABA001-DK a zároveň do BOA001-DK.

**Comment by helena-oks** [comment]
Děkuji, již vše OK.

**Comment by helena-oks** [comment]
Zjistila jsem (po přeindexování) chybu: neplatí, že se to týká pouze pro záznamů, které mají kód financování iop nebo ndk-u!

**Comment by helena-oks** [comment]
Pokračování je na #689 - bude dořešeno tam.
