### ISSUE TITLE
odstraňovat z dotazu mezery na začátku a na konci pole

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#670]
Pokud je na začátku nebo na konci údaje zadávaného jako dotaz mezera nebo skrytý znak, vyhledání neproběhne správně.

**Comment by lucka-pavlova** [comment]
Alberto prosím odhadni pracnost.

**Comment by lucka-pavlova** [comment]
@albertoh prosim okomentuj.

**Comment by helena-oks** [comment]
Funguje, děkujeme.
