### ISSUE TITLE
RD nenajde cnb001812964

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#671]
V www.registrdigitalizace.cz při rozšířeném hledání podle čČNB  zadám cnb001812964 a nenajde se žádný záznam. Proč? V reliefu vidím rovnou výsledky dva  (Pr000036867, Pr000413996). Ty výsledek  potřebujeme vidět komplet, když jsou evidentně v databázi.

**Comment by helena-oks** [comment]
Dnes ve 14h jsem 2 záznamy našla přes ččnb jak jednoduchým, tak rozšířeným vyhledáváním.  Chyba nejspíš nebyla v tom, že se neaktualizoval uživatelský web, protože aspoň jeden ze záznamů je starý. Lze zjistit, čím to bylo?

**Comment by indrakm** [comment]
Ano, dnes 6:10 jsem našel oba záznamy taky, ale včera jistojistě ne. Tento problém se nám opakuje často, kdy paní doktorka Jelínková pošle do registru něco, co tam nenašla a ono to tam ve skutečnosti je. Čím to je? Pr000036867, Pr000413996 jsou záznamy z roku 2015, 2016 - to se mi taky na aktualizaci nějak nezdá. Dříve jsem si myslel, že jde o chyby přípravy, ale teď to vypadá na pěkně děravý systém.

**Comment by albertoh** [comment]
Mam podezreni, ze to se stalo ted v pondeli rano. V NKP ted jsou jiste problemy se servery, a reindexace je pomalejsi.
O vikendu probiha celkovy reindex, ktery zmaze vsechno a reindexuje z databaze. Je mozne, ze rano jeste to nebylo hotove. 
 Zmenil jsem reindexace: misto nedeli na sobotu.

**Comment by indrakm** [comment]
Aha, děkuji, to dává smysl a hodně asi i vysvětluje. Bylo by dobré, aby v pondělí ráno už byla vždy reindexace hotová. U nás se začíná pravidelně 06:00 :)

**Comment by lucka-pavlova** [comment]
Vyřešeno změnou času reindexace.
