### ISSUE TITLE
nechodí importní hlášení RD

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#672]
Asi od pátku nechodí importní hlášení z RD, Ivan Ljubka to hlásil do servicedesku NK a já taky. Na čí straně je prosím problém? Zakládání do linky NDK kvůli tomu celé stojí. Děkuji

**Comment by MKortus** [comment]
Dobrý den,
email ze servicedesku nedorazil, proto jsme o ničem nevěděli. 
Importer byl restartován a teď již soubory zpracoval i ty dnešní.

S pozdravem Marek Kortus

**Comment by MKortus** [comment]
Ještě jsem koukal do servicedesku a tam žádný požadavek na nás není, proto ani nepřišel email.
S pozdravem Marek Kortus

**Comment by indrakm** [comment]
Díky za restart. No ty tickety se asi zasekly v NK. Já ho tam totiž nemůžu nikomu přidělit jenom odeslat a před chvílí mi přišla notifikace, že ten můj ticket se "eskaloval" teprve na Zdeno Vozára. Příště bude jistější to napsat na jejich servisdesj a rovnou asi i sem. Děkuji

**Comment by helena-oks** [comment]
Ještě mám dotaz, jestli se nějaké importy "neztratily", protože prvních několik notifikačních mailů (nejen pro NK a MZK, též třeba pro ABG001) obsahovalo chybové hlášky typu: 
"Nepodařilo se identifikovat přispěvatele dle SIGLA 20190322133154, nebo přispěvatel neměl řádně vyplněna všechna pole. Soubor má špatný formát stavu: 20190326114146_20190322133154_aba001_p_dg45_20190322".
Protože od všech těchto knihoven chodí maily automatem, chyba v názvu ani datech asi být nemohla - nebo se něco "rozbilo cestou"? Dalo by se to prověřit a zjistit příčinu? Dík.

**Comment by indrakm** [comment]
za BOA001 to vypadá dobře, na chybu jsme nenarazil. Jinak kolega Vozár tam teď s týmem řeší ještě další akutní problémy. Myslím, že ta komunikace se vyřeší. Teď se to bohužel zase nějak seběhlo :(

**Comment by SykoraLukas** [comment]
Neztratilo se nic, chyba je na naší straně. Zapomněli jsme ze souborů, které neprošly odstranit časovou značku a při opětovném spuštění aplikace se tato časová značka brala jako Sigla. Soubory jsme již přejmenovali a spustili znovu.
