### ISSUE TITLE
nefunguje frontend 

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#673]
nefunkční frontend RD

**Comment by albertoh** [comment]
Server 10.1.20.48 kde je index neodpovida.
Nejde se na ne prihlasit pres ssh

**Comment by indrakm** [comment]
@JanMeritus Zdeno, udělejte s tím něco prosím. U nás se s registrem dělá každý den od 6:00. Apríl nám začíná pekně co :D

**Comment by JanMeritus** [comment]
@indrakm riesime to

**Comment by JanMeritus** [comment]
z nasi strany vyrieseno

**Comment by albertoh** [comment]
Uz to bezi. 
Spustil jsem reindex, abychom meli jistotu, ze mame posledni data. Predpokladam, ze za cca 1hod reindex bude hotovy.
Aplikace bude fungovat i mezitim.

**Comment by SykoraLukas** [comment]
RD pro editory a UniImporter je nastartovaný

**Comment by indrakm** [comment]
Děkujeme za vyřešení
