### ISSUE TITLE
výmaz importu CBA001 z  26.04.2019

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#675]
Prosím o vyexportování (a uschování pro jistotu) a poté smazání záznamů:
...from predloha where sigla1='CBA001' and zaldate='26.04.2019'

(špatně vytvořený soubor zaslaný při testování na ftp)

**Comment by helena-oks** [comment]
Záznamy do RD nepatří, je velmi nutné je co nejdřív vymazat!

**Comment by SykoraLukas** [comment]
Záznamy odstraněny

**Comment by helena-oks** [comment]
Děkuji.
