### ISSUE TITLE
nový uživatel do Reliefu

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#678]
Prosím založit nové uživatele - podrobnosti a hesla zaslány mailem (4.6., opakovaně 12.6.).

1/  bezovam- podle loginu pana Ljubky 
2/ lia001 - editační práva jen na záznamy LIA001 (sigla1) a bez práva mazat

**Comment by SykoraLukas** [comment]
Uživatelé vytvořeni, podrobnosti viz mailová kouminkace (kvůli bezpečnosti to nepíši sem).

**Comment by helena-oks** [comment]
Děkuji.
