### ISSUE TITLE
vyhledávání - chybějící záznamy pod ABA001-DK

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#679]
Pod DK NK - nová digitalizace (ABA001-DK) se nyní zařazuje jen necelých 10.000 záznamů, ve skutečnosti tam patří záznamy všech záznamů, které mají napojený objekt z tabulky digobjekt. 
![DK-NDK](https://user-images.githubusercontent.com/13746425/60426523-1bf75e80-9bf5-11e9-9bfb-01791505129b.jpg)

select count(*) from predloha,DIGOBJEKT
where predloha.id = DIGOBJEKT.rpredloha_digobjekt and sigla1='ABA001';
= 85784 záznamů jen ABA001, bez BOA001!

Došlo k tomu zřejmě po vyřešení issue 669. 
https://github.com/NKCR-INPROVE/registrdigitalizace/issues/669

Všechny záznamy, co teď mají 2 odkazy se stejným UUID, by měly spadat do ABA001-DK a zároveň do BOA001-DK.

**Comment by albertoh** [comment]
Reindexovano. Otestujte, prosim.
Pokud je to OK, i #669 by bylo mozne uzavrit

**Comment by helena-oks** [comment]
Děkuji, je to v pořádku.

**Comment by helena-oks** [comment]
Dnes jsem náhodou zjistila, že se opět vrátila situace, co jsem hlásila na začátku. Je třeba tedy přeindexovávat pravidelně? Obrázek je z dnešního dne, téměř stejný jako minulý.
![DK-NDK2](https://user-images.githubusercontent.com/13746425/62538516-4cb16000-b853-11e9-9e78-a505744605c2.jpg)

**Comment by helena-oks** [comment]
Indexování už je asi OK.
