### ISSUE TITLE
neprobíhají importy!!

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#680]
Dnes neproběhl import souborů, které se z ftp adresáře stáhly. Poslední import byl podle evidence importů 28.6. , takže to možná nefunguje už déle...

**Comment by indrakm** [comment]
nefunguje to tak cca 2 dny! Zrovna jsem chtěl na to založit issue.

**Comment by indrakm** [comment]
Pořád to ještě nejede, proč? Předpokládám, že je potřeba jen něco restartovat nebo došlo někde místo.

**Comment by lucka-pavlova** [comment]
@SykoraLukas , prosim okomentuj

**Comment by JanMeritus** [comment]
@lucka-pavlova poprosim o urychlenie riesenia

**Comment by lucka-pavlova** [comment]
Dobrý den, 
Lukáš problém řeší. Bohužel z Logů zatím není jasné, kde je problém. @SykoraLukas , napiš prosím poslední stav do issue. Díky, Lucka

**Comment by helena-oks** [comment]
Dnes proběhlo větší množství importů - předpokládám, že ne všechny byly nové (z dneška). Proběhly i importy CBA001, které jsem "podstrčila" znovu. Prosím, NEPOSÍLAT ručně soubory začínající cba001..., pokud by se někde "našly"! 

Lze ověřit na straně NK a MZK, jestli ještě jsou nějaké soubory z minulého týdne, co dosud neprošly?

**Comment by SykoraLukas** [comment]
Nastal problém s místem, který by již měl být vyřešený. Souborz (kromě CBA) jsem již nechal doimportovat, tedy by měli být v reliefu všechny soubory z tohoto a minulého týdne.

@JanMeritus  prosím zkotrolujte, že máte naimportované všechny vaše soubory. Již by tam měli být ze včera.

**Comment by indrakm** [comment]
v MZK je vše ok. Děkuji!

**Comment by helena-oks** [comment]
V NK zdá se taky nic nepostrádají. Pokud jde o problém s místem: teď nám možná dost "zasviňují" disky velké xml soubory cba001, z nichž se stejně téměř nic neimportuje. Mohly by mazat - pro jistotu s časovým odstupem, třeba za měsíc.

**Comment by SykoraLukas** [comment]
Tam nešlo o problem s celkovou pameti ale s pameti pri zpracovani zaznamu. Jedna z knihoven mela cca 5 MB file a do toho soubory z CBA (cca 15 souboru po 500 KB) což zpusobilo kolabs importeru. Nyni je to už opravene. 

Soubory CBA se muzou jednou za cas mazat, to jak budete chtit. Nějak se domluvime.
