### ISSUE TITLE
oprava a výmaz přes sql dávky

### ISSUE THREAD

**Issue by helena-oks** [NKCR-INPROVE/registrdigitalizace#682]
Prosím spustit dávkové úpravy:
1/ ccnb_dod0619.txt - oprava v předlohách - v příkazech je nutno nahradit DATUM

2/ uuid_del0709.txt - seznam uuid - je třeba vymazat záznamy s těmito uuid v tabulce digobjekt,  včetně vazeb na předlohy

[ccnb_dod0619.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/3371603/ccnb_dod0619.txt)
[uuid_del0709.txt](https://github.com/NKCR-INPROVE/registrdigitalizace/files/3371605/uuid_del0709.txt)

**Comment by SykoraLukas** [comment]
Úprava dat:
- Pole001 000739971 upraveno 4x
- Poslední řádek upraveno 38x
- Ostatní upraveno 1x

Smazány byly všechny ptřebné záznamy.

**Comment by helena-oks** [comment]
Děkuji.
