### ISSUE TITLE
Registr digitalizace - IMPORT

### ISSUE THREAD

**Issue by indrakm** [NKCR-INPROVE/registrdigitalizace#684]
Dnes nepřišel tradiční importní výpis po 11-té hodině. Zase došlo místo? Přijde něco zítra? Asi těžko říct no..

**Comment by indrakm** [comment]
zdá se, že už je vše v pořádku

**Comment by JanMeritus** [comment]
@indrakm proc tomu tak bolo?

**Comment by SykoraLukas** [comment]
Chybou bylo nenačtení FTP. Opraveno restartem aplikace
